languageCode = "fa-IR"
copyRight = "۲۰۱۹ © پوریا جهانبخش"

[params]
  sitename = "Pouriya"
  disableWebFonts = false
  siteGitURL = "https://github.com/pouriya/psite"
  desc = "نوشته های یک برنامه‌نویس معمولی"
  comments = true


[[menu.main]]
    name = "<about/>"
    url  = "BASEURL/en/about"

[[menu.main]]
    name = "<en/>"
    url  = "BASEURL/en"
