languageCode = "en-US"
copyRight = "2019 © Pouriya Jahanbakhsh"

[params]
  sitename = "Pouriya"
  disableWebFonts = false
  siteGitURL = "https://github.com/pouriya/psite"
  desc = "A person who writes computer code"
  comments = true

[[menu.main]]
    name = "<about/>"
    url  = "/about"

[[menu.main]]
    name = "<fa/>"
    url  = "BASEURL/fa"
